version: "3.8"

services:
  backend:
    container_name: Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app  # Sync backend files
      - /app/tmp  # Ensure tmp is writable for Air
    env_file:
      - backend/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Ensure node_modules are not overwritten
    networks:
      - app-network
    environment:
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true  # Enable polling to detect file changes
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
