root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "bin/main"
  cmd = "go build -o ./bin/main ./cmd/server"
  delay = 1000
  exclude_dir = ["bin", "vendor", "scripts"]
  exclude_file = []
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  log = "build-errors.log"
  poll = true
  poll_interval = 500
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true